### ISSUE TITLE
Crush on updateLocation

### ISSUE THREAD

**Issue by erasta** [argosp/trialdash#73]
Calling updateLocation crushes
To reproduce: 
- Get to the leaflet map api
- Press one device on the left (probably d1)
- Click the map
- If didn't crush, click the map again
- See the crush on the console

A video was sent on whatsapp group

**Comment by erasta** [comment]
https://youtu.be/_k-Z6OqGfg4

**Comment by erasta** [comment]
Related crushes happen on
- https://github.com/argosp/trialdash/blob/a63c65a15604e93f4921b2fb660191f602aa6779/src/components/TrialContext/TrialForm/TrialDevices/index.jsx#L105
- https://github.com/argosp/trialdash/blob/e1a29fa9b66fa58f7e4eb47dd89b62aa0aebd6f1/src/components/DevicePlanner/index.jsx#L22

**Comment by liorkesos** [comment]
@shimlinnovate please assign to whomever is on this ?

**Comment by YehuditGrinwald** [comment]
@erasta  still? I did the same step as you describe but not reproduced

**Comment by erasta** [comment]
> @erasta still? I did the same step as you describe but not reproduced

you have to wait a bit until the error shows up, now it looks like this:
![image](https://user-images.githubusercontent.com/7118772/85565510-dfa7e400-b637-11ea-952e-51670331f422.png)

**Comment by YehuditGrinwald** [comment]
@erasta  
1.while steps by step with your video example don't have the icon when locate device on the map.
2. where  the new coordinates should save in the json trial tree:
trial.properties (it's null for  right now)
OR
trial.entites.propreties (has the updates  coordinates)
?

**Comment by erasta** [comment]
@YehuditGrinwald 
> 1.while step by step with your video example - I see that I don't have the icon when locate device on the map.

Which icon?
When you switch to the map you set the location of a device by clicking the device on the list and clicking the map.

> 2. where the new coordinates should save in the json trial tree:
> trial.properties (it's null for right now)
> OR
> trial.entites.propreties (Array of updates coordinates, save in DB) ?

You tell me.
I'm not changing the `trial`, only the `devices`, and to access it I use `client.query` or `updateLocation` functions you supply as props.
The trial json tree is out of my scope.

**Comment by erasta** [comment]
After talking to @YehuditGrinwald we decided that we would check manually if the graphql mutation sent for the update location did indeed update the mongoDB

**Comment by erasta** [comment]
Is there any updates on this?
@YehuditGrinwald

**Comment by YehuditGrinwald** [comment]
@erasta   DB issue was fixed - [ I merged updates ](https://github.com/argosp/trialgraph/commit/a96defceca51d13908ff1f4d0e8cfcb7d438fbca)to `dev`. 
Should also merge to master? what br dev environment works with?

**Comment by YehuditGrinwald** [comment]
@yehudarav @shimlinnovate fixed. changes was uploaded to the dev environment

**Comment by erasta** [comment]
Still not fixed when used on the internet.
Are the devices locations saved to the database?

**Comment by erasta** [comment]
I believe that the mutation on `trialMutationUpdate` doesn't work, as it takes the properties from the wrong trial.
Please put a breakpoint at and see:
https://github.com/argosp/trialdash/blob/1546086fb0a08ee5ecd6b94f031525a0145020c0/src/components/TrialContext/TrialForm/utils/trialMutationUpdate.js#L7

**Comment by YehuditGrinwald** [comment]
@erasta  After debug `trialMutationUpdate` I see that now only new trials (that created after my fix)  save the devices location right in DB and old trials not usable anymore- because the entities that was saved before my fix- broke the structure.
also I checked the trails query and we got right data. Now only issue with devises table - it does not display all data. as you can see in attachment screenshot.

![image](https://user-images.githubusercontent.com/24703036/89894924-96115980-dbe3-11ea-9640-9a665867f70d.png)
please let me know if I was clear.

**Comment by erasta** [comment]
> @erasta After debug `trialMutationUpdate` I see that now only new trials (that created after my fix) save the devices location right in DB and old trials not usable anymore- because the entities that was saved before my fix- broke the structure.
> also I checked the trails query and we got right data. Now only issue with devises table - it does not display all data. as you can see in attachment screenshot.

Thank you.
So you're saying that the existing code saves the devices correctly?
Please feel free to delete any trial that was broken.
Is `NewTestTrial` supposed to be working well?
If so, I will debug my display so to show the saved devices correctly.

**Comment by YehuditGrinwald** [comment]
> > @erasta After debug `trialMutationUpdate` I see that now only new trials (that created after my fix) save the devices location right in DB and old trials not usable anymore- because the entities that was saved before my fix- broke the structure.
> > also I checked the trails query and we got right data. Now only issue with devises table - it does not display all data. as you can see in attachment screenshot.
> 
> Thank you.
> So you're saying that the existing code saves the devices correctly?
> Please feel free to delete any trial that was broken.
> Is `NewTestTrial` supposed to be working well?
> If so, I will debug my display so to show the saved devices correctly.

@erasta  yes, `NewTestTrial` supposed to be working well.

Gonna create mongo query for delete the trials that was broken.

**Comment by erasta** [comment]
Apparently the locations are not saved on the device, but on the trial, and still as strings that require `JSON.parse()`
Can't understand why that is, but now it is working.

<img width="874" alt="Screen Shot 2020-08-11 at 9 00 10 PM" src="https://user-images.githubusercontent.com/7118772/89932149-dab5e880-dc15-11ea-90c7-dc88e3cca43a.png">

**Comment by YehuditGrinwald** [comment]
@yehudarav Please check and close
